# Generated by Django 2.0.2 on 2018-04-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puser',
            name='phoneno',
            field=models.CharField(max_length=13),
        ),
    ]
