# Generated by Django 2.0.2 on 2018-03-17 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180317_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
