# Generated by Django 2.0.2 on 2018-03-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20180317_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key='true', serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phoneno', models.IntegerField()),
                ('bdate', models.DateTimeField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
