# Generated by Django 2.0.2 on 2018-03-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_puser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.CharField(max_length=30, primary_key='true', serialize=False)),
                ('show_id', models.ForeignKey(on_delete='true', to='login.Show')),
                ('user_id', models.ForeignKey(on_delete='true', to='login.Puser')),
            ],
        ),
        migrations.CreateModel(
            name='TicketOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.ForeignKey(on_delete='true', to='login.Offers')),
                ('ticket_id', models.ForeignKey(on_delete='true', to='login.Ticket')),
            ],
        ),
    ]
