# Generated by Django 2.0.2 on 2018-03-20 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_cinema_movie_show_ticket_ticketoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='bdate',
        ),
    ]
