# Generated by Django 2.0.2 on 2018-03-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20180320_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('cinema_id', models.CharField(max_length=30, primary_key='true', serialize=False)),
                ('cinema_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('phoneno', models.IntegerField()),
                ('adderess', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.CharField(max_length=30, primary_key='true', serialize=False)),
                ('movie_name', models.CharField(max_length=50)),
                ('cinema_id', models.ForeignKey(on_delete='true', to='login.Cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('offer_id', models.CharField(max_length=30, primary_key='true', serialize=False)),
                ('offer_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('show_id', models.CharField(max_length=30, primary_key='true', serialize=False)),
                ('time', models.DateTimeField()),
                ('cinema_id', models.ForeignKey(on_delete='true', to='login.Cinema')),
                ('movie_id', models.ForeignKey(on_delete='true', to='login.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.CharField(max_length=30, primary_key='true', serialize=False)),
                ('show_id', models.ForeignKey(on_delete='true', to='login.Show')),
                ('user_id', models.ForeignKey(on_delete='true', to='login.Puser')),
            ],
        ),
        migrations.CreateModel(
            name='TicketOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.ForeignKey(on_delete='true', to='login.Offers')),
                ('ticket_id', models.ForeignKey(on_delete='true', to='login.Ticket')),
            ],
        ),
    ]
