# Generated by Django 2.0.2 on 2018-03-20 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_cinema_movie_offers_show_ticket_ticketoffer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinema',
            old_name='adderess',
            new_name='address',
        ),
    ]
