# Generated by Django 2.0.2 on 2018-04-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20180320_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cinema_id',
        ),
        migrations.RemoveField(
            model_name='show',
            name='cinema_id',
        ),
        migrations.RemoveField(
            model_name='show',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='show_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='ticketoffer',
            name='offer_id',
        ),
        migrations.RemoveField(
            model_name='ticketoffer',
            name='ticket_id',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Show',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='TicketOffer',
        ),
    ]
