# Generated by Django 2.0.2 on 2018-04-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20180402_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.CharField(max_length=30, primary_key='true', serialize=False)),
                ('movie_name', models.CharField(max_length=50)),
                ('movie_rating', models.IntegerField()),
                ('cinema_id', models.ForeignKey(on_delete='true', to='login.Cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('show_id', models.CharField(max_length=30, primary_key='true', serialize=False)),
                ('time', models.DateTimeField()),
                ('price1', models.IntegerField()),
                ('price2', models.IntegerField()),
                ('seat', models.CharField(max_length=100)),
                ('cinema_id', models.ForeignKey(on_delete='true', to='login.Cinema')),
                ('movie_id', models.ForeignKey(on_delete='true', to='login.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.CharField(max_length=30, primary_key='true', serialize=False)),
                ('show_id', models.ForeignKey(on_delete='true', to='login.Show')),
                ('user_id', models.ForeignKey(on_delete='true', to='login.Puser')),
            ],
        ),
        migrations.CreateModel(
            name='TicketOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.ForeignKey(on_delete='true', to='login.Offers')),
                ('ticket_id', models.ForeignKey(on_delete='true', to='login.Ticket')),
            ],
        ),
    ]
